name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # test against latest update of each LTS Java version:
        java: [ 8, 11, 17 ]
        # test against major operating systems
        os: [ubuntu-20.04, windows-latest, macos-latest]
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Check formatting
        if: ${{ matrix.java != 8 }} # Spotless does not support Java 8
        run: mvn spotless:check
      - name: Run tests
        run: mvn test
